version: '3.8'

services:
  # Frontend - Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mythofy-mail-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mythofy-mail-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend - Rust API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mythofy-mail-backend
    ports:
      - "8080:8080"
    environment:
      - MAILCOW_API_URL=${MAILCOW_API_URL}
      - MAILCOW_API_KEY=${MAILCOW_API_KEY}
      - IMAP_HOST=${IMAP_HOST}
      - IMAP_PORT=${IMAP_PORT}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=mysql://mailuser:mailpass@mysql:3306/mythofy_mail
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
    networks:
      - mythofy-mail-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis - Caching
  redis:
    image: redis:7-alpine
    container_name: mythofy-mail-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - mythofy-mail-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MySQL - User metadata and app data
  mysql:
    image: mysql:8.0
    container_name: mythofy-mail-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mythofy_mail
      - MYSQL_USER=mailuser
      - MYSQL_PASSWORD=mailpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - mythofy-mail-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx - Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: mythofy-mail-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - mythofy-mail-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
  mysql-data:

networks:
  mythofy-mail-network:
    driver: bridge
